name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Build package
        run: npm run build
        
      - name: Check build output
        run: |
          if [ ! -f "dist/nodes/PersistentVariables/PersistentVariables.node.js" ]; then
            echo "Build failed - main node file not found"
            exit 1
          fi
          if [ ! -f "dist/nodes/PersistentVariables/SqliteService.js" ]; then
            echo "Build failed - SQLite service file not found"
            exit 1
          fi
          echo "Build successful - all files present"
